name: Deploy app

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

env:
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  SENTRY_ORG: ${{ vars.SENTRY_ORG }}
  SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT }}
  VITE_API_BASE_URL: ${{ vars.VITE_API_BASE_URL }}
  VITE_SENTRY_DSN: ${{ vars.VITE_SENTRY_DSN }}
  VITE_SENTRY_ENV: ${{ vars.VITE_SENTRY_ENV }}
  VITE_OAUTH_AUTHORIZATION_URL: ${{ vars.VITE_OAUTH_AUTHORIZATION_URL }}
  VITE_OAUTH_CLIENT_ID: ${{ vars.VITE_OAUTH_CLIENT_ID }}
  VITE_STORAGE_BASE_URL: ${{ vars.VITE_STORAGE_BASE_URL }}

jobs:
  deploy:
    name: Deploy react app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'yarn'

      - run: npm pkg delete scripts.prepare

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Typechecking
        run: yarn ci:typecheck

      - name: Validate environment
        run: yarn ci:validate-env

      - name: Build project
        run: yarn build

      - name: Remove source maps
        run: rm -rf dist/**/*.js.map

      - name: Debug build output
        run: ls -la dist

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/**/*

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4