name: Deploy app

on:
  push:
    branches: [main]

env:
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  SENTRY_ORG: ${{ vars.SENTRY_ORG }}
  SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT }}
  VITE_SENTRY_DSN: ${{ vars.VITE_SENTRY_DSN }}
  VITE_SENTRY_ENV: ${{ vars.VITE_SENTRY_ENV }}
  VITE_CLARITY_PROJECT_ID: ${{ vars.VITE_CLARITY_PROJECT_ID }}
  VITE_STORAGE_BASE_URL: ${{ vars.VITE_STORAGE_BASE_URL }}

jobs:
  deploy:
    name: Deploy react app on AWS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
        
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - run: npm pkg delete scripts.prepare

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Typechecking
        run: pnpm ci:typecheck

      - name: Validate environment
        run: pnpm ci:validate-env

      - name: Build project
        run: pnpm build

      - name: Remove source maps
        run: rm -rf dist/**/*.js.map

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        run: aws s3 sync dist/ s3://${{ secrets.BUCKET_NAME }} --delete --exact-timestamps

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CF_ID }} --paths /index.html